### ISSUE TITLE
Branch/Fork

### ISSUE THREAD

**Issue by Phil1972** [OpenSkyPlus/OpenSkyPlus#4]
Hi,

@OpenSkyPlus,
Not sure if you saw my post in the discussion, but I would be ready to push a branch in the repo with fixes and Handedness support.  What is the procedure that would be ok with you?

Thanks,

**Comment by OpenSkyPlus** [comment]
Awesome! I'll open the repo up so you can submit a pull request to the main branch. Always happy to have contributions here.
