### ISSUE TITLE
OpenSky Installer won't load

### ISSUE THREAD

**Issue by Whitecheezy** [OpenSkyPlus/OpenSkyPlus#5]
I followed the instructions I found, but am having an issue where when I  run the open sky installer it shows the logo then nothing happens.  I tried disabling the firewalls and also running in admin mode.  i am running windows 11.  any help is appreciated.

**Comment by OpenSkyPlus** [comment]
I haven't seen this one before. It's been tested on Windows 11, so I don't think that is the issue. Do you have any kind of anti virus installed on your system? Can you post a video of the behavior?

**Comment by Whitecheezy** [comment]
[Newest.zip](https://github.com/OpenSkyPlus/OpenSkyPlus/files/15463517/Newest.zip)
This is what was happening. Thanks for any help. All Firewalls and Virus Software were completely turned off.

**Comment by Zjohnson18** [comment]
Same thing is happening to me

**Comment by Zjohnson18** [comment]
Is there another location we can download from?

**Comment by Whitecheezy** [comment]
I was able to get mine to work recently..
I updated the .NET framework for Windows.
Manually installed an old No-putting version and then the installer worked fine. Not sure which one was the issue.

**Comment by Zjohnson18** [comment]
Where can i download an old version?

**Comment by OpenSkyPlus** [comment]
@Zjohnson18 pinned messages on the #skytrak_plus channel. Check them and scroll

**Comment by OpenSkyPlus** [comment]
@Whitecheezy won't be downloading any zips from here. Please post video to youtube or similar hosting service
